version: '3.8'

services:
    sqlserver: 
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Passw0rd1234
        restart: unless-stopped

    postgres:
        restart: unless-stopped
        ports:
            - 5432:5432   
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=username
            - POSTGRES_DB=identity
     
    mongo:
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME:root
            - MONGO_INITDB_ROOT_PASSWORD:password

    mongo-express:
        restart: unless-stopped
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME:root
            - ME_CONFIG_MONGODB_ADMINPASSWORD:password

    identity:
        ports:
            - 1000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped

    chat:
        ports:
            - 3000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped
    
    musicians:
        ports:
            - 2000:80 
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped