version: '3.8'

services:
    sqlserver: 
        container_name: SqlServer
        image: mcr.microsoft.com/mssql/server:2022-latest

    postgres:
        container_name: Postgres
        image: postgres:latest
     
    mongo:
        container_name: Mongo
        image: mongo

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo

    identity:
        container_name: Identity
        build:
            context: "."
            dockerfile: "/Services/Identity/Identity.API/Dockerfile"
        depends_on:
            - kafka
            - postgres

    chat:
        container_name: Chat
        build:
            context: "."
            dockerfile: "/Services/Chat/Chat.API/Dockerfile"
        depends_on:
            - kafka
            - sqlserver

    musicians:
        container_name: Musicians
        build:
            context: "."
            dockerfile: "/Services/Musicians/Musicians.API/Dockerfile"
        depends_on:
            - kafka
            - mongo

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        depends_on:
            - zookeeper

    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop
        depends_on:
            - kafka
    
    redis:
        image: redis:latest
        container_name: Redis