version: '3.8'

services:
    sqlserver: 
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Passw0rd1234
        restart: unless-stopped

    postgres:
        restart: unless-stopped
        ports:
            - 5432:5432   
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=username
            - POSTGRES_DB=identity
     
    mongo:
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME:root
            - MONGO_INITDB_ROOT_PASSWORD:password

    mongo-express:
        restart: unless-stopped
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME:root
            - ME_CONFIG_MONGODB_ADMINPASSWORD:password

    identity:
        ports:
            - 1000:80
        volumes:
            - ./Logs/IdentityLogs:/app/logs
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped

    chat:
        ports:
            - 3000:80
        volumes:
            - ./Logs/ChatLogs:/app/logs 
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped
    
    musicians:
        ports:
            - 2000:80 
        volumes:
            - ./Logs/MusicianLogs:/app/logs
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped
   
    zookeeper:
        ports:
            - "2181:2181" 
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
            KAFKA_BROKER_ID: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1

    kafdrop:
        ports:
            - 9000:9000
        environment:
            KAFKA_BROKERCONNECT: kafka:9092
    
    logstash01:
        user: root
        ports:
            - "5044:5044" 
        volumes:
            - ./Elastic/Certs:/usr/share/logstash/config/certs 
            - ./Elastic/LogstashData:/usr/share/logstash/data
            - ./Elastic/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        environment:
            - xpack.monitoring.enabled=false
            - ELASTIC_USER=elastic
            - ELASTIC_PASSWORD=elastic123
            - ELASTIC_HOSTS=https://es01:9200 

    filebeat:
        user: root
        volumes:
            - ./Elastic/Certs:/usr/share/filebeat/certs
            - ./Logs:/usr/share/filebeat/logs_ingest/ 
            - ./Elastic/FilebeatData:/usr/share/filebeat/data
            - ./Elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        environment:
            - ELASTIC_USER=elastic
            - ELASTIC_PASSWORD=elastic123
            - ELASTIC_HOSTS=https://es01:9200
            - KIBANA_HOSTS=http://kibana:5601
            - LOGSTASH_HOSTS=http://logstash01:9600 

    kibana:
        volumes:
            - ./Elastic/Certs:/usr/share/kibana/config/certs
            - ./Elastic/KibanaData:/usr/share/kibana/data
        ports:
            - 5601:5601
        environment:
            - SERVERNAME=kibana
            - ELASTICSEARCH_HOSTS=https://es01:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=kibana123
            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
            - XPACK_SECURITY_ENCRYPTIONKEY=c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2
            - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2
            - XPACK_REPORTING_ENCRYPTIONKEY=c34d38b3a14956121ff2170e5030b471551370178f43e5626eec58b04a30fae2
        mem_limit: 1073741824

    es01:
       volumes:
         - ./Elastic/Certs:/usr/share/elasticsearch/config/certs
         - ./Elastic/Data:/usr/share/elasticsearch/data
       ports:
         - 9200:9200
       environment:
         - node.name=es01
         - cluster.name=logsearch
         - discovery.type=single-node
         - ELASTIC_PASSWORD=elastic123
         - bootstrap.memory_lock=true
         - xpack.security.enabled=true
         - xpack.security.http.ssl.enabled=true
         - xpack.security.http.ssl.key=certs/es01/es01.key
         - xpack.security.http.ssl.certificate=certs/es01/es01.crt
         - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
         - xpack.security.transport.ssl.enabled=true
         - xpack.security.transport.ssl.key=certs/es01/es01.key
         - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
         - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
         - xpack.security.transport.ssl.verification_mode=certificate
         - xpack.license.self_generated.type=basic
       mem_limit: 1073741824
    
    elasticsetup:
        volumes:
            - ./Elastic/Certs:/usr/share/elasticsearch/config/certs
        user: "0"