version: '3.8'

services:
    #sqlserver: 
    #    container_name: SqlServer
    #    image: mcr.microsoft.com/mssql/server:2022-latest
    #    ports:
    #      - 1433:1433
    #    environment:
    #      - ACCEPT_EULA=Y
    #      - MSSQL_SA_PASSWORD=Passw0rd
    #    restart: unless-stopped

    postgres:
        container_name: Postgres
        image: postgres:latest
        ports:
            - 5432:5432   
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=username
            - POSTGRES_DB=identity
        restart: unless-stopped
            
    identity:
        container_name: Identity
        build:
            context: "."
            dockerfile: "/Services/Identity/Identity.API/Dockerfile"
        ports:
            - 1000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped
    