version: '3.8'

services:
    sqlserver: 
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - MSSQL_SA_PASSWORD=Passw0rd1234
        restart: unless-stopped

    postgres:
        restart: unless-stopped
        ports:
            - 5432:5432   
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=username
            - POSTGRES_DB=identity
     
    mongo:
        restart: unless-stopped
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME:root
            - MONGO_INITDB_ROOT_PASSWORD:password

    mongo-express:
        restart: unless-stopped
        ports:
            - 8081:8081
        environment: 
            - ME_CONFIG_MONGODB_ADMINUSERNAME:root
            - ME_CONFIG_MONGODB_ADMINPASSWORD:password

    identity:
        ports:
            - 1000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped

    chat:
        ports:
            - 3000:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker 
        restart: unless-stopped
    
    musicians:
        ports:
            - 2000:80 
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        restart: unless-stopped
   
    zookeeper:
        ports:
            - "2181:2181" 
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        ports:
            - "9092:9092"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
            KAFKA_BROKER_ID: 1
            KAFKA_MIN_INSYNC_REPLICAS: 1

    kafdrop:
        ports:
            - 9000:9000
        environment:
            KAFKA_BROKERCONNECT: kafka:9092